In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
a + 1

array([2, 3, 4, 5])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:

%timeit [i**2 for i in range(1000)]

450 µs ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
a = np.arange(1000)
%timeit a**2

2.18 µs ± 273 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
a.ndim

1

In [10]:
a.shape

(1000,)

In [11]:
a.size

1000

In [12]:
a.max()

999

* 1D => Vector
* 2D => Matrix
* 3D => Tensor

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [24]:
# uniform distribution
np.random.rand(3)

array([0.36921115, 0.36668202, 0.42769441])

In [25]:
# gaussian distribution
np.random.randn(3)

array([-1.71446638, -1.17838174, -0.78587128])

In [28]:
np.random.randint(3)

1

In [29]:
np.random.randint(3,6)

5

In [30]:
np.array([1+2j, 3+4j])

array([1.+2.j, 3.+4.j])

In [31]:
a.dtype

dtype('int32')

In [33]:
a[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[-10:]

array([990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [35]:
b = a[:10]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b[0]= 100
a[:10]

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [37]:
c = a[:10].copy()
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [38]:
c[0] = 1
a[:10]

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
b[::-1]

array([  9,   8,   7,   6,   5,   4,   3,   2,   1, 100])

In [41]:
np.shares_memory(a,b)

True

In [42]:
np.shares_memory(a,c)

False

In [43]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [44]:
b[b%2 == 0]

array([100,   2,   4,   6,   8])