## Numpy Notes and Practice

#### link: http://scipy-lectures.org/intro/numpy/array_object.html

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
print(a)

[1 2 3 4]


In [6]:
a + 1

array([2, 3, 4, 5])

In [7]:
a

array([1, 2, 3, 4])

### Numpy - memory Efficiency

In [8]:
L = range(1000)
%timeit [i**2 for i in L]

400 µs ± 69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

2.25 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.ndim

1

In [13]:
a.shape

(10,)

In [14]:
a.size

10

In [15]:
a.max()

9

In [16]:
a.min()

0

In [17]:
len(a)

10

* 1D => Vector
* 2D => Matrix
* 3D => Tensor

In [18]:
# evenly spaced
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0,1,5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
# uniform distribution
np.random.rand(3)

array([0.17561563, 0.48635577, 0.48356667])

In [27]:
# gaussian distribution
np.random.randn(3)

array([-1.20757423,  0.74215672,  0.23523274])

In [28]:
np.random.randint(3)

1

In [29]:
np.random.randint(3,6)

5

In [30]:
np.random.seed(42)

In [34]:
# returns uninitialized array
np.empty([2,2])

array([[0.2, 0.4],
       [0.6, 0.8]])

In [30]:
np.array([1+2j, 3+4j])

array([1.+2.j, 3.+4.j])

In [31]:
a.dtype

dtype('int32')

In [33]:
a[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[-10:]

array([990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [35]:
b = a[:10]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b[0]= 100
a[:10]

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [37]:
c = a[:10].copy()
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [38]:
c[0] = 1
a[:10]

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [39]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [40]:
b[::-1]

array([  9,   8,   7,   6,   5,   4,   3,   2,   1, 100])

In [41]:
np.shares_memory(a,b)

True

In [42]:
np.shares_memory(a,c)

False

In [43]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [44]:
b[b%2 == 0]

array([100,   2,   4,   6,   8])

In [45]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [47]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [49]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
a-b

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [51]:
a*b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
a == b

array([False,  True, False, False, False, False, False, False, False,
       False])

In [53]:
a > b

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [54]:
np.array_equal(a,b)

False

In [55]:
np.logical_or(a,b)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
np.logical_and(a,b)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [57]:
np.sum(a)

45

In [58]:
a.sum()

45

In [59]:
a.min()

0

In [60]:
a.max()

9

In [61]:
np.max(a)

9

In [62]:
np.min(a)

0

In [63]:
np.argmax(a)

9

In [64]:
np.argmin(a)

0

In [65]:
np.all([True, True])

True

In [66]:
np.all([False, True])

False

In [67]:
np.any([True, False])

True

In [68]:
np.any([False, False])

False

In [69]:
np.mean(a)

4.5

In [70]:
np.median(a)

4.5

In [71]:
np.std(a)

2.8722813232690143

In [72]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [75]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [76]:
np.tile(a,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [77]:
a

array([1, 2, 3])

In [78]:
a.shape

(3,)

In [82]:
a = a[:, np.newaxis]
a.shape

(3, 1)

In [83]:
a

array([[1],
       [2],
       [3]])

In [84]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [86]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [88]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
np.sort(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
a = np.array([4,2,3,1])
a

array([4, 2, 3, 1])

In [95]:
np.sort(a)

array([1, 2, 3, 4])