## Numpy Notes and Practice

#### link: http://scipy-lectures.org/intro/numpy/array_object.html

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
print(a)

[1 2 3 4]


In [6]:
a + 1

array([2, 3, 4, 5])

In [7]:
a

array([1, 2, 3, 4])

### Numpy - memory Efficiency

In [8]:
L = range(1000)
%timeit [i**2 for i in L]

400 µs ± 69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

2.25 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a.ndim

1

In [13]:
a.shape

(10,)

In [14]:
a.size

10

In [15]:
a.max()

9

In [16]:
a.min()

0

In [17]:
len(a)

10

* 1D => Vector
* 2D => Matrix
* 3D => Tensor

In [18]:
# evenly spaced
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0,1,5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
# uniform distribution
np.random.rand(3)

array([0.17561563, 0.48635577, 0.48356667])

In [27]:
# gaussian distribution
np.random.randn(3)

array([-1.20757423,  0.74215672,  0.23523274])

In [28]:
np.random.randint(3)

1

In [29]:
np.random.randint(3,6)

5

In [30]:
np.random.seed(42)

In [34]:
# returns uninitialized array
np.empty([2,2])

array([[0.2, 0.4],
       [0.6, 0.8]])

In [35]:
a = np.array([1+2j, 3+4j])
a

array([1.+2.j, 3.+4.j])

In [36]:
a.dtype

dtype('complex128')

In [37]:
a = np.array([1,2,3])
a.dtype

dtype('int32')

In [38]:
a = np.array([1.,2.,3.])
a.dtype

dtype('float64')

In [39]:
a = np.arange(25)
a[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a[-10:]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
b = a[:10]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Copying Numpy Arrays

In [43]:
# assigning like this will also change the original
b[0]= 100
a[:10]

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [44]:
c = a[:10].copy()
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [45]:
c[0] = 1
a[:10]

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [46]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [48]:
## reversing
b[::-1]

array([  9,   8,   7,   6,   5,   4,   3,   2,   1, 100])

In [49]:
a = np.array([True, False, True])
a.dtype

dtype('bool')

In [50]:
a = np.array(['python','numpy','pandas'])
a.dtype

dtype('<U6')

In [51]:
a = np.array(['python','numpy','pandas','scikit-learn'])
a.dtype

dtype('<U12')

#### In the above the dtype responds with the largest string size

In [52]:
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

## Fancy Indexing
<img src='http://scipy-lectures.org/_images/numpy_indexing.png' />

In [54]:
a = np.array([1,2,3])
b = a
np.shares_memory(a,b)

True

In [55]:
c = a.copy()
np.shares_memory(a,c)

False

In [56]:
b

array([1, 2, 3])

In [57]:
b[b%2 == 0]

array([2])

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [60]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [61]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
a-b

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [63]:
a*b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
a == b

array([False,  True, False, False, False, False, False, False, False,
       False])

In [65]:
a > b

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
np.array_equal(a,b)

False

In [67]:
np.logical_or(a,b)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [68]:
np.logical_and(a,b)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [69]:
np.sum(a)

45

In [70]:
a.sum()

45

In [71]:
a.min()

0

In [72]:
a.max()

9

In [73]:
np.max(a)

9

In [74]:
np.min(a)

0

In [77]:
# gives out the index
np.argmax(a)

9

In [78]:
# gives out the index
np.argmin(a)

0

In [79]:
np.all([True, True])

True

In [80]:
np.all([False, True])

False

In [81]:
np.any([True, False])

True

In [82]:
np.any([False, False])

False

In [83]:
np.mean(a)

4.5

In [84]:
np.median(a)

4.5

In [85]:
np.std(a)

2.8722813232690143

In [86]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [88]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [90]:
np.tile(a,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [93]:
# 4 indicates the rows, 2 indicates the repitition
np.tile(a,(4,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [94]:
a

array([1, 2, 3])

In [95]:
a.shape

(3,)

In [96]:
a = a[:, np.newaxis]
a.shape

(3, 1)

In [97]:
a

array([[1],
       [2],
       [3]])

In [98]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [100]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [102]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
np.sort(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
a = np.array([4,2,3,1])
a

array([4, 2, 3, 1])

In [107]:
np.sort(a)

array([1, 2, 3, 4])

### random

In [112]:
# uniform distribution
np.random.rand()

0.17052412368729153

In [109]:
np.random.rand(5)

array([0.95071431, 0.73199394, 0.59865848, 0.15601864, 0.15599452])

In [111]:
np.random.rand(5,5)

array([[0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449],
       [0.96990985, 0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184, 0.45606998, 0.78517596],
       [0.19967378, 0.51423444, 0.59241457, 0.04645041, 0.60754485]])

In [113]:
# guassian distribution
np.random.randn()

-0.600638689918805

In [114]:
np.random.randn(5)

array([-0.29169375, -0.60170661,  1.85227818, -0.01349722, -1.05771093])

In [115]:
np.random.randn(5,5)

array([[ 0.82254491, -1.22084365,  0.2088636 , -1.95967012, -1.32818605],
       [ 0.19686124,  0.73846658,  0.17136828, -0.11564828, -0.3011037 ],
       [-1.47852199, -0.71984421, -0.46063877,  1.05712223,  0.34361829],
       [-1.76304016,  0.32408397, -0.38508228, -0.676922  ,  0.61167629],
       [ 1.03099952,  0.93128012, -0.83921752, -0.30921238,  0.33126343]])

In [116]:
np.random.randint(1,10)

2

In [117]:
np.random.randint(1,10,10)

array([1, 7, 7, 8, 5, 3, 8, 6, 3, 1])

In [118]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [120]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [124]:
# element at row 1 and column 0
arr[1,0]

5

In [125]:
# element at row 1 and column 0
arr[1][0]

5

In [126]:
arr[-1,-1]

24