In [1]:
import numpy as np

### using np.where 

In [3]:
arr = np.random.rand(4,4)
arr

array([[0.51085437, 0.05091971, 0.40838938, 0.32187125],
       [0.1748698 , 0.04241233, 0.94457232, 0.69067158],
       [0.10860551, 0.26222557, 0.35073104, 0.82750063],
       [0.96013561, 0.04153258, 0.48298976, 0.36832426]])

In [4]:
arr>0.5

array([[ True, False, False, False],
       [False, False,  True,  True],
       [False, False, False,  True],
       [ True, False, False, False]])

### 1st arg is condition, if True takes 2nd argument, else takes 3rd argument

In [5]:
np.where(arr>0.5, 1, 0)

array([[1, 0, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])

### mathematical and statistical methods

In [9]:
arr = np.random.randn(3,5)
arr

array([[ 0.04130039, -0.65536851, -0.28492298, -0.8123759 ,  0.64025622],
       [ 0.03220593,  0.93913178,  0.46036165,  0.28323042, -0.01232718],
       [ 1.63454647,  0.29380707, -1.05160552, -2.39362668,  0.91543834]])

### calculating mean

In [11]:
arr.mean()

0.002003433542319999

In [12]:
np.mean(arr)

0.002003433542319999

### calculating sum

In [14]:
arr.sum()

0.030051503134799984

In [15]:
np.sum(arr)

0.030051503134799984

In [16]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### calculates mean row and column wise when u give axes

In [17]:
arr.mean(axis=0)

array([4., 5., 6., 7.])

In [18]:
arr.mean(axis=1)

array([1.5, 5.5, 9.5])

In [19]:
np.sum(arr, axis=1)

array([ 6, 22, 38])

In [20]:
np.sum(arr, axis=0)

array([12, 15, 18, 21])

### using cumsum and cumprod

In [21]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

### calculates the sum incrementally with every value

In [22]:
arr.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

### calculates prod incrementally with every value

In [24]:
arr.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

### any and all methods, useful for boolean arrays

In [25]:
arr_bool = np.array([True, False, False, True, True])
arr_bool

array([ True, False, False,  True,  True])

### produces value true if any value is true

In [26]:
np.any(arr_bool)

True

In [28]:
arr_bool.any()

True

In [ ]:
### produces false

In [27]:
np.all(arr_bool)

False

In [29]:
arr_bool.all()

False

### sorting arrays

In [36]:
arr = np.random.randn(3,5)
arr

array([[ 0.02766903, -0.21457433,  0.44608191, -0.0563337 , -0.59330082],
       [ 1.34959427, -1.84200334, -0.01493687, -0.15374365,  1.53201676],
       [-2.36722991, -1.34393588, -1.61047945, -1.10842003,  1.50759041]])

### sorts in place

In [39]:
arr.sort()

In [40]:
arr

array([[-0.59330082, -0.21457433, -0.0563337 ,  0.02766903,  0.44608191],
       [-1.84200334, -0.15374365, -0.01493687,  1.34959427,  1.53201676],
       [-2.36722991, -1.61047945, -1.34393588, -1.10842003,  1.50759041]])

### this returns a new copy and not sorts in place like the arr.sort() does

In [37]:
np.sort(arr)

array([[-0.59330082, -0.21457433, -0.0563337 ,  0.02766903,  0.44608191],
       [-1.84200334, -0.15374365, -0.01493687,  1.34959427,  1.53201676],
       [-2.36722991, -1.61047945, -1.34393588, -1.10842003,  1.50759041]])

In [38]:
arr

array([[ 0.02766903, -0.21457433,  0.44608191, -0.0563337 , -0.59330082],
       [ 1.34959427, -1.84200334, -0.01493687, -0.15374365,  1.53201676],
       [-2.36722991, -1.34393588, -1.61047945, -1.10842003,  1.50759041]])

### unique values of an array

In [41]:
arr = np.array([1,2,1,3,5,6,1,2,4,5,6])
arr

array([1, 2, 1, 3, 5, 6, 1, 2, 4, 5, 6])

### returns the unique values of the array

In [43]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

### python alternative for the above

In [44]:
sorted(set(arr))

[1, 2, 3, 4, 5, 6]

### computing if one array element is present in another, returns boolean array

In [45]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
arr2 = np.array([2,4,7])
arr2

array([2, 4, 7])

### checks if the values of arr1 are present in arr2

In [47]:
np.in1d(arr1,arr2)

array([False,  True, False,  True, False, False,  True])

### computes the common elements in both arr1 and arr2

In [49]:
np.intersect1d(arr1,arr2)

array([2, 4, 7])

### File operations, load and save functions

In [50]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### it creates a my_array.npy file on the disk

In [51]:
np.save('my_array', arr)

### loading data from the file

In [53]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### LINEAR ALGEBRA
#### Matrix functions

In [54]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Dot product 

In [58]:
np.dot(arr, arr.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [57]:
arr.dot(arr.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

### Most of the function are available in numpy.linalg package

In [77]:
from numpy.linalg import inv, qr, det

### calculates the inverse of the matrix

In [65]:
inv(arr.dot(arr.T))

array([[-1.50443522e+14,  3.00887044e+14, -1.50443522e+14],
       [ 3.00887044e+14, -6.01774088e+14,  3.00887044e+14],
       [-1.50443522e+14,  3.00887044e+14, -1.50443522e+14]])

### calcaultes the sum of the diagonal elements

In [74]:
np.trace(arr.dot(arr.T))

506

### det, eig is for calculating determinant and eigenvalues and eigenvectors

In [78]:
det(arr.dot(arr.T))

-2.1270440605979823e-12

### generating pseudo random numbers, using randomState and seed

In [79]:
np.random.seed(10)

### randomstate is used to generate numbers isolated from others

In [91]:
np.random.RandomState(100)

In [92]:
np.random.randn(10)

array([-1.58494101,  1.05535316, -1.92657911,  0.69858388, -0.74620143,
       -0.15662666, -0.19363594,  1.13912535,  0.36221796, -0.59091299])

In [93]:
np.random.randn(10)

array([ 0.38936304, -0.52699615, -0.51430791,  0.89760917,  0.98925209,
        0.25922513, -0.02419319,  0.35849666, -0.37754636,  0.69563116])

In [94]:
np.random.randn(10)

array([ 1.02484465,  1.70775544, -1.96711722, -0.87095667, -1.10682548,
        0.27512366, -0.36445614, -1.16515347, -1.34306988,  1.45339286])

### random walk

In [96]:
nsteps = 1000
draws = np.random.randint(0,2, size=nsteps)
steps = np.where(draws > 0 , 1, -1)
walk = steps.cumsum()

In [103]:
walk

array([  1,   2,   1,   0,   1,   2,   3,   2,   1,   0,  -1,  -2,  -1,
         0,   1,   2,   1,   2,   3,   2,   1,   0,   1,   0,   1,   2,
         1,   2,   1,   0,  -1,  -2,  -1,   0,  -1,  -2,  -3,  -2,  -1,
         0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -7,  -8,  -7,  -6,
        -5,  -6,  -7,  -8,  -7,  -8,  -7,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -3,  -2,  -1,   0,   1,   2,   3,   2,   1,   2,   3,   2,
         3,   4,   5,   4,   5,   4,   5,   4,   3,   4,   5,   4,   5,
         6,   7,   6,   7,   8,   7,   8,   9,  10,   9,  10,   9,   8,
         9,  10,  11,  12,  13,  12,  11,  12,  13,  12,  11,  10,   9,
         8,   7,   6,   5,   4,   3,   4,   3,   4,   3,   4,   3,   4,
         3,   4,   5,   4,   5,   6,   7,   6,   5,   4,   3,   2,   1,
         0,  -1,   0,  -1,  -2,  -3,  -2,  -3,  -2,  -3,  -4,  -5,  -6,
        -5,  -4,  -3,  -2,  -3,  -2,  -1,   0,   1,   0,   1,   2,   3,
         2,   1,   2,   1,   0,  -1,  -2,  -3,  -2,  -1,  -2,  -

In [97]:
walk.min()

-36

In [98]:
walk.max()

13

### gives the index when he walked 10 steps from the origin

In [102]:
np.argmax(walk>10)

106