<a href="https://colab.research.google.com/github/Vikas-KM/machine-learning/blob/master/tensorflow_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensorflow Introduction

In [6]:
import tensorflow as tf

In [7]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Creating Tensors

In [8]:
str1 = tf.Variable('This is a string', tf.string)
str1

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>

In [9]:
int1 = tf.Variable(231, tf.int32)
int1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=231>

In [11]:
flt1 = tf.Variable(243.24, tf.float64)
flt1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=243.24>

Rank or Degree of the tensors - ie the dimensions

In [12]:
tf.rank(str1)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [13]:
str2 = tf.Variable([['This'],['is']], tf.string)
tf.rank(str2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
str3 = tf.Variable(['this'], tf.string)
tf.rank(str3)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Shape of the tensors

In [15]:
str1.shape

TensorShape([])

In [16]:
str2.shape

TensorShape([2, 1])

In [17]:
str3.shape

TensorShape([1])

In [18]:
str4 = tf.Variable([['this'],['ok','ok']], tf.string)

ValueError: ignored

changing the shape of the tensors

In [19]:
tensor1 = tf.ones([1,2,3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [21]:
tensor2 = tf.reshape(tensor1, [3,2,1])
tensor2

<tf.Tensor: shape=(3, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [23]:
tensor3 = tf.reshape(tensor1, [3,-1])
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

Types of Tensors


*   Variables
*   Constants
*   Placeholder
*   Sparse Tensor

Except Variable all are immutable

