In [1]:
import numpy as np
import pandas as pd

### Hierarchial Indexing

In [9]:
data = pd.Series(np.random.randn(9),
              index=[['a','a','a','b','b','c','c','d','d'],[1,2,3,4,5,6,7,8,9]])
data

a  1   -0.489182
   2   -0.428769
   3   -0.843021
b  4    0.781283
   5   -1.438964
c  6   -0.030500
   7   -0.631414
d  8    0.403452
   9    0.577119
dtype: float64

In [10]:
data.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3, 4, 5, 6, 7, 8, 9]],
           codes=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [11]:
data['b']

4    0.781283
5   -1.438964
dtype: float64

In [12]:
data['b':'d']

b  4    0.781283
   5   -1.438964
c  6   -0.030500
   7   -0.631414
d  8    0.403452
   9    0.577119
dtype: float64

In [13]:
data.loc['b']

4    0.781283
5   -1.438964
dtype: float64

In [14]:
data.loc[:,2]

a   -0.428769
dtype: float64

In [15]:
data.unstack()

1         2         3         4         5       6         7  \
a -0.489182 -0.428769 -0.843021       NaN       NaN     NaN       NaN   
b       NaN       NaN       NaN  0.781283 -1.438964     NaN       NaN   
c       NaN       NaN       NaN       NaN       NaN -0.0305 -0.631414   
d       NaN       NaN       NaN       NaN       NaN     NaN       NaN   

          8         9  
a       NaN       NaN  
b       NaN       NaN  
c       NaN       NaN  
d  0.403452  0.577119

In [16]:
data.unstack().stack()

a  1   -0.489182
   2   -0.428769
   3   -0.843021
b  4    0.781283
   5   -1.438964
c  6   -0.030500
   7   -0.631414
d  8    0.403452
   9    0.577119
dtype: float64

### Hierarchial Indexing in DataFrame

In [17]:
df = pd.DataFrame(np.arange(12).reshape((3,4)),
                 index=[['a','b','b'],[1,2,1]],
                 columns=[['Maha','Kar','Maha','Kar'],[1,2,1,2]])
df

Maha Kar Maha Kar
       1   2    1   2
a 1    0   1    2   3
b 2    4   5    6   7
  1    8   9   10  11

In [18]:
df.index.names

FrozenList([None, None])

In [19]:
df.index.names=['key1','key2']

In [20]:
df.columns.names=['state','key3']

In [21]:
df

state     Maha Kar Maha Kar
key3         1   2    1   2
key1 key2                  
a    1       0   1    2   3
b    2       4   5    6   7
     1       8   9   10  11

In [22]:
df['Maha']

key3       1   1
key1 key2       
a    1     0   2
b    2     4   6
     1     8  10

### Reordering and Sorting

In [23]:
df

state     Maha Kar Maha Kar
key3         1   2    1   2
key1 key2                  
a    1       0   1    2   3
b    2       4   5    6   7
     1       8   9   10  11

In [24]:
df.swaplevel('key1','key2')

state     Maha Kar Maha Kar
key3         1   2    1   2
key2 key1                  
1    a       0   1    2   3
2    b       4   5    6   7
1    b       8   9   10  11

In [25]:
df.sort_index()

state     Maha Kar Maha Kar
key3         1   2    1   2
key1 key2                  
a    1       0   1    2   3
b    1       8   9   10  11
     2       4   5    6   7

In [26]:
df

state     Maha Kar Maha Kar
key3         1   2    1   2
key1 key2                  
a    1       0   1    2   3
b    2       4   5    6   7
     1       8   9   10  11

In [27]:
df.sum(level='key2')

state Maha Kar Maha Kar
key3     1   2    1   2
key2                   
1        8  10   12  14
2        4   5    6   7

In [28]:
df.sum(level='key3', axis=1)

key3        1   2
key1 key2        
a    1      2   4
b    2     10  12
     1     18  20

In [33]:
df = pd.DataFrame({
    'a':range(7),
    'b':range(7,0,-1),
    'c':['one','two','one','two','one','one','two'],
    'd':[0,1,2,3,0,1,2],
})
df

a  b    c  d
0  0  7  one  0
1  1  6  two  1
2  2  5  one  2
3  3  4  two  3
4  4  3  one  0
5  5  2  one  1
6  6  1  two  2

### indexing the DataFrame Columns

In [35]:
df1 = df.set_index(['c','d'])
df1

a  b
c   d      
one 0  0  7
two 1  1  6
one 2  2  5
two 3  3  4
one 0  4  3
    1  5  2
two 2  6  1

In [36]:
df2 = df.set_index(['c','d'], drop=False)
df2

a  b    c  d
c   d              
one 0  0  7  one  0
two 1  1  6  two  1
one 2  2  5  one  2
two 3  3  4  two  3
one 0  4  3  one  0
    1  5  2  one  1
two 2  6  1  two  2

### resetting the Indexs as columns

In [38]:
df1.reset_index()

c  d  a  b
0  one  0  0  7
1  two  1  1  6
2  one  2  2  5
3  two  3  3  4
4  one  0  4  3
5  one  1  5  2
6  two  2  6  1

### Combining and merging datasets

In [40]:
df1 = pd.DataFrame({
    'key1':['a','b','c','b','a','a','c'],
    'data1':range(7),
})
df1

key1  data1
0    a      0
1    b      1
2    c      2
3    b      3
4    a      4
5    a      5
6    c      6

In [41]:
df2 = pd.DataFrame({
    'key1':['a','b','d'],
    'data2':range(3),
})
df2

key1  data2
0    a      0
1    b      1
2    d      2

### merging df1 and df2

In [42]:
pd.merge(df1,df2)

key1  data1  data2
0    a      0      0
1    a      4      0
2    a      5      0
3    b      1      1
4    b      3      1

### specify which columns to merge

In [43]:
pd.merge(df1,df2,on='key1')

key1  data1  data2
0    a      0      0
1    a      4      0
2    a      5      0
3    b      1      1
4    b      3      1

### if column names are different

In [44]:
df3 = pd.DataFrame({
    'key1':['a','b','c','b','a','a','c'],
    'data1':range(7),
})
df3

key1  data1
0    a      0
1    b      1
2    c      2
3    b      3
4    a      4
5    a      5
6    c      6

In [45]:
df4 = pd.DataFrame({
    'key2':['a','b','d'],
    'data2':range(3),
})
df4

key2  data2
0    a      0
1    b      1
2    d      2

In [46]:
pd.merge(df3,df4, left_on='key1', right_on='key2')

key1  data1 key2  data2
0    a      0    a      0
1    a      4    a      0
2    a      5    a      0
3    b      1    b      1
4    b      3    b      1

### merge takes intersection, union is available

In [48]:
pd.merge(df1,df2, how='outer')

key1  data1  data2
0    a    0.0    0.0
1    a    4.0    0.0
2    a    5.0    0.0
3    b    1.0    1.0
4    b    3.0    1.0
5    c    2.0    NaN
6    c    6.0    NaN
7    d    NaN    2.0

In [49]:
df1 = pd.DataFrame({
    'key':['a','b','a','b','c','a','c'],
    'data1':range(7)
})
df1

key  data1
0   a      0
1   b      1
2   a      2
3   b      3
4   c      4
5   a      5
6   c      6

In [51]:
df2 = pd.DataFrame({
    'key':['a','b','a','a','d'],
    'data2':range(5),
})
df2

key  data2
0   a      0
1   b      1
2   a      2
3   a      3
4   d      4

### left includes all the left elements

In [52]:
pd.merge(df1,df2,on='key', how='left')

key  data1  data2
0    a      0    0.0
1    a      0    2.0
2    a      0    3.0
3    b      1    1.0
4    a      2    0.0
5    a      2    2.0
6    a      2    3.0
7    b      3    1.0
8    c      4    NaN
9    a      5    0.0
10   a      5    2.0
11   a      5    3.0
12   c      6    NaN

### right takes all the right elements

In [53]:
pd.merge(df1,df2, on='key', how='right')

key  data1  data2
0    a    0.0      0
1    a    2.0      0
2    a    5.0      0
3    a    0.0      2
4    a    2.0      2
5    a    5.0      2
6    a    0.0      3
7    a    2.0      3
8    a    5.0      3
9    b    1.0      1
10   b    3.0      1
11   d    NaN      4

In [54]:
pd.merge(df1,df2,on='key')

key  data1  data2
0    a      0      0
1    a      0      2
2    a      0      3
3    a      2      0
4    a      2      2
5    a      2      3
6    a      5      0
7    a      5      2
8    a      5      3
9    b      1      1
10   b      3      1

### many-many takes the cartesian product of rows

### to merge multiple columns

In [56]:
df1 = pd.DataFrame({
    'key1':['a','b','c'],
    'data1':range(3),
    'key2':['foo','bar','foo']
})
df1

key1  data1 key2
0    a      0  foo
1    b      1  bar
2    c      2  foo

In [57]:
df2 = pd.DataFrame({
    'key1':['a','b','d'],
    'data2':range(3),
    'key2':['bar','foo','bar'],
})
df2

key1  data2 key2
0    a      0  bar
1    b      1  foo
2    d      2  bar

In [60]:
pd.merge(df1,df2, on=['key1','key2'], how='outer')

key1  data1 key2  data2
0    a    0.0  foo    NaN
1    b    1.0  bar    NaN
2    c    2.0  foo    NaN
3    a    NaN  bar    0.0
4    b    NaN  foo    1.0
5    d    NaN  bar    2.0

### merging on Index

In [62]:
left = pd.DataFrame({
    'key':['a','b','a','b','c'],
    'value':range(5),
})
left

key  value
0   a      0
1   b      1
2   a      2
3   b      3
4   c      4

In [63]:
right=pd.DataFrame({
    'value':[3,5]
},
    index=['a','b']
)
right

value
a      3
b      5

In [65]:
pd.merge(left,right, left_on='key', right_index=True)

key  value_x  value_y
0   a        0        3
2   a        2        3
1   b        1        5
3   b        3        5

In [66]:
pd.merge(left,right, left_on='key', right_index=True, how='outer')

key  value_x  value_y
0   a        0      3.0
2   a        2      3.0
1   b        1      5.0
3   b        3      5.0
4   c        4      NaN

In [72]:
left

key  value
0   a      0
1   b      1
2   a      2
3   b      3
4   c      4

In [73]:
right

value
a      3
b      5

In [75]:
left.index=['a','b','c','a','b']

In [76]:
left

key  value
a   a      0
b   b      1
c   a      2
a   b      3
b   c      4

In [77]:
right

value
a      3
b      5

### Concatenating along Axis

In [80]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
np.concatenate([arr,arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [82]:
np.concatenate([arr,arr], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### concatenating in pandas

In [83]:
s1 = pd.Series([0,1], index=['a','b'])
s1

a    0
b    1
dtype: int64

In [84]:
s2 = pd.Series([2,3,4], index=['c','d','e'])
s2

c    2
d    3
e    4
dtype: int64

In [85]:
s3 = pd.Series([5,6],index=['f','g'])
s3

f    5
g    6
dtype: int64

In [87]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [88]:
pd.concat([s1,s2,s3], axis=1)

C:\Users\Vikas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [89]:
pd.concat([s1,s2,s3], keys=['one','two','three'])

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [90]:
pd.concat([s1,s2,s3], axis=1, keys=['one','two','three'])

C:\Users\Vikas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [91]:
result = pd.concat([s1,s2,s3], keys=['one','two','three'])
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [92]:
result.unstack()

a    b    c    d    e    f    g
one    0.0  1.0  NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  2.0  3.0  4.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0

### combining data with overlap

In [98]:
a=pd.Series([0,2,5,np.nan,0,np.nan,1],
           index=['a','b','c','d','e','f','g'])
a

a    0.0
b    2.0
c    5.0
d    NaN
e    0.0
f    NaN
g    1.0
dtype: float64

In [99]:
b=pd.Series([0,np.nan,3,1,np.nan,2,1],
           index=['a','b','c','d','e','f','g'])
b

a    0.0
b    NaN
c    3.0
d    1.0
e    NaN
f    2.0
g    1.0
dtype: float64

In [100]:
np.where(pd.isnull(a),b,a)

array([0., 2., 5., 1., 0., 2., 1.])

### below does same as above, combining columns

In [101]:
b.combine_first(a)

a    0.0
b    2.0
c    3.0
d    1.0
e    0.0
f    2.0
g    1.0
dtype: float64

### Reshaping and Pivoting

In [103]:
data = pd.DataFrame(np.arange(6).reshape(2,3),
                   index=pd.Index(['a','b'],name='States'),
                    columns=pd.Index(['one','two','three'], name='numbers'),
                   )
data

numbers  one  two  three
States                  
a          0    1      2
b          3    4      5

In [110]:
res = data.stack()
res

States  numbers
a       one        0
        two        1
        three      2
b       one        3
        two        4
        three      5
dtype: int32

In [108]:
data

numbers  one  two  three
States                  
a          0    1      2
b          3    4      5

In [113]:
res.unstack()

numbers  one  two  three
States                  
a          0    1      2
b          3    4      5

In [114]:
res

States  numbers
a       one        0
        two        1
        three      2
b       one        3
        two        4
        three      5
dtype: int32

### unstacking using different levels

In [116]:
res.unstack(0)

States   a  b
numbers      
one      0  3
two      1  4
three    2  5

In [117]:
data

numbers  one  two  three
States                  
a          0    1      2
b          3    4      5

In [118]:
data = pd.read_csv('./../examples/macrodata.csv')
data.head()

year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959.0      1.0  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959.0      2.0  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959.0      3.0  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959.0      4.0  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960.0      1.0  2847.699    1770.5  331.722   462.199   1955.5  29.54   

      m1  tbilrate  unemp      pop  infl  realint  
0  139.7      2.82    5.8  177.146  0.00     0.00  
1  141.7      3.08    5.1  177.830  2.34     0.74  
2  140.5      3.82    5.3  178.657  2.74     1.09  
3  140.0      4.33    5.6  179.386  0.27     4.06  
4  139.6      3.50    5.2  180.007  2.31     1.19

In [119]:
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter, name='date')
periods

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', name='date', length=203, freq='Q-DEC')

In [120]:
columns=pd.Index(['readlgdp','infl','unemp'], name='item')
columns

Index(['readlgdp', 'infl', 'unemp'], dtype='object', name='item')

In [121]:
data=data.reindex(columns=columns)

In [122]:
data.index=periods.to_timestamp('D','end')

In [123]:
ldata = data.stack().reset_index().rename(columns={0:'value'})

In [124]:
data.head()

item                           readlgdp  infl  unemp
date                                                
1959-03-31 23:59:59.999999999       NaN  0.00    5.8
1959-06-30 23:59:59.999999999       NaN  2.34    5.1
1959-09-30 23:59:59.999999999       NaN  2.74    5.3
1959-12-31 23:59:59.999999999       NaN  0.27    5.6
1960-03-31 23:59:59.999999999       NaN  2.31    5.2

In [125]:
ldata.head()

date   item  value
0 1959-03-31 23:59:59.999999999   infl   0.00
1 1959-03-31 23:59:59.999999999  unemp   5.80
2 1959-06-30 23:59:59.999999999   infl   2.34
3 1959-06-30 23:59:59.999999999  unemp   5.10
4 1959-09-30 23:59:59.999999999   infl   2.74

### pivot method

In [127]:
pivoted = ldata.pivot('date','item','value')
pivoted

item                           infl  unemp
date                                      
1959-03-31 23:59:59.999999999  0.00    5.8
1959-06-30 23:59:59.999999999  2.34    5.1
1959-09-30 23:59:59.999999999  2.74    5.3
1959-12-31 23:59:59.999999999  0.27    5.6
1960-03-31 23:59:59.999999999  2.31    5.2
1960-06-30 23:59:59.999999999  0.14    5.2
1960-09-30 23:59:59.999999999  2.70    5.6
1960-12-31 23:59:59.999999999  1.21    6.3
1961-03-31 23:59:59.999999999 -0.40    6.8
1961-06-30 23:59:59.999999999  1.47    7.0
1961-09-30 23:59:59.999999999  0.80    6.8
1961-12-31 23:59:59.999999999  0.80    6.2
1962-03-31 23:59:59.999999999  2.26    5.6
1962-06-30 23:59:59.999999999  0.13    5.5
1962-09-30 23:59:59.999999999  2.11    5.6
1962-12-31 23:59:59.999999999  0.79    5.5
1963-03-31 23:59:59.999999999  0.53    5.8
1963-06-30 23:59:59.999999999  2.75    5.7
1963-09-30 23:59:59.999999999  0.78    5.5
1963-12-31 23:59:59.999999999  2.46    5.6
1964-03-31 23:59:59.999999999  0.13    5.5
1964-06-30 23:59:59.999999999  0.90    5.2
1964-09-30 23:59:59.999999999  1.29    5.0
1964-12-31 23:59:59.999999999  2.05    5.0
1965-03-31 23:59:59.999999999  1.28    4.9
1965-06-30 23:59:59.999999999  2.54    4.7
1965-09-30 23:59:59.999999999  0.89    4.4
1965-12-31 23:59:59.999999999  2.90    4.1
1966-03-31 23:59:59.999999999  4.99    3.9
1966-06-30 23:59:59.999999999  2.10    3.8
...                             ...    ...
2002-06-30 23:59:59.999999999  1.56    5.8
2002-09-30 23:59:59.999999999  2.66    5.7
2002-12-31 23:59:59.999999999  3.08    5.8
2003-03-31 23:59:59.999999999  1.31    5.9
2003-06-30 23:59:59.999999999  1.09    6.2
2003-09-30 23:59:59.999999999  2.60    6.1
2003-12-31 23:59:59.999999999  3.02    5.8
2004-03-31 23:59:59.999999999  2.35    5.7
2004-06-30 23:59:59.999999999  3.61    5.6
2004-09-30 23:59:59.999999999  3.58    5.4
2004-12-31 23:59:59.999999999  2.09    5.4
2005-03-31 23:59:59.999999999  4.15    5.3
2005-06-30 23:59:59.999999999  1.85    5.1
2005-09-30 23:59:59.999999999  9.14    5.0
2005-12-31 23:59:59.999999999  0.40    4.9
2006-03-31 23:59:59.999999999  2.60    4.7
2006-06-30 23:59:59.999999999  3.97    4.7
2006-09-30 23:59:59.999999999 -1.58    4.7
2006-12-31 23:59:59.999999999  3.30    4.4
2007-03-31 23:59:59.999999999  4.58    4.5
2007-06-30 23:59:59.999999999  2.75    4.5
2007-09-30 23:59:59.999999999  3.45    4.7
2007-12-31 23:59:59.999999999  6.38    4.8
2008-03-31 23:59:59.999999999  2.82    4.9
2008-06-30 23:59:59.999999999  8.53    5.4
2008-09-30 23:59:59.999999999 -3.16    6.0
2008-12-31 23:59:59.999999999 -8.79    6.9
2009-03-31 23:59:59.999999999  0.94    8.1
2009-06-30 23:59:59.999999999  3.37    9.2
2009-09-30 23:59:59.999999999  3.56    9.6

[203 rows x 2 columns]

### melt method - inverse of pivot

In [128]:
df = pd.DataFrame({
    'key':['foo','bar','baz'],
    'A':[0,1,2],
    'B':[1,2,3],
    'C':[2,3,4],
})
df

key  A  B  C
0  foo  0  1  2
1  bar  1  2  3
2  baz  2  3  4

In [129]:
res = pd.melt(df, ['key'])
res

key variable  value
0  foo        A      0
1  bar        A      1
2  baz        A      2
3  foo        B      1
4  bar        B      2
5  baz        B      3
6  foo        C      2
7  bar        C      3
8  baz        C      4

In [131]:
reshaped = res.pivot('key','variable','value')
reshaped

variable  A  B  C
key              
bar       1  2  3
baz       2  3  4
foo       0  1  2

In [132]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  1  2  3
1         baz  2  3  4
2         foo  0  1  2