### indexing and slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8]

array([5, 6, 7])

In [4]:
arr[5:8] = 10
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

### this doesnot copy the array, but just references it

In [5]:
arr_slice = arr[5:8]
arr_slice

array([10, 10, 10])

In [6]:
arr_slice[0] = 100
arr_slice

array([100,  10,  10])

### arr is also changed when arr_slice is changed

In [7]:
arr

array([  0,   1,   2,   3,   4, 100,  10,  10,   8,   9])

### [:] selects all the elements

In [8]:
arr_slice[:] = 25
arr_slice

array([25, 25, 25])

### indexing and slicing with 2D array

In [9]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### selects the first row and 2 column element

In [10]:
arr2d[0][1]

2

### selecting all the elemnts of row 1

In [11]:
arr2d[:][1]

array([4, 5, 6])

In [14]:
arr2d[1,:]

array([4, 5, 6])

### the above method arr(row,column) is used mostly

### selecting all elements of column 1

In [15]:
arr2d[:,1]

array([2, 5, 8])

### Boolean Indexing

In [16]:
arr = np.arange(30).reshape(6,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [18]:
arr_bool = arr[arr > 14]
arr_bool

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [32]:
mask = names == 'Bob'
mask

array([ True, False, False,  True, False, False, False])

### we can use this mask for further calculations

### Fancy Indexing

In [33]:
arr2d = np.zeros((8,4))
arr2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
for i in range(8):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

### astype to convert from one array datatype to another

In [35]:
arr2d = arr2d.astype(np.int32)
arr2d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

### first array selects the row, second selects the corressponding column

In [37]:
arr2d[[1,3,6],[1,3,0]]

array([1, 3, 6])

In [38]:
arr_copy = arr2d[[1,2],[2,3]]
arr_copy

array([1, 2])

In [39]:
arr_copy[:] = 100
arr_copy

array([100, 100])

In [40]:
arr2d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

### fancy indexing copies the array, not just reference

### Tanspose and swapping

In [41]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [44]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### swapping axes

In [48]:
arr.swapaxes(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [50]:
arr.swapaxes(0,1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### swapping with 3D array

In [51]:
arr3d = np.arange(24).reshape(2,3,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### basically takes the (1,2) refers to 2nd and 3rd in reshape(2,3,4)

In [52]:
arr3d.swapaxes(1,2)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [53]:
arr3d.swapaxes(0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

### uniary and binary functions

In [54]:
arr2d

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [55]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### find the maximum element

In [65]:
np.amax(arr3d)

23

### find the minimum element

In [58]:
np.amin(arr3d)

0

In [2]:
arr = np.array([9,6,8,2,0,1])

### returns the index of the maximum element

In [62]:
np.argmax(arr)

0

### returns the index of the minimum element

In [63]:
np.argmin(arr)

4

### find the range between max and min values
#### max = 9, min = 0  range = 9-0 = 9

In [4]:
np.ptp(arr)

9

### modf function returns fractional and integral parts of floating array

In [68]:
arr_float = np.array([1.23,4.56,7.89], dtype='float64')
arr_float

array([1.23, 4.56, 7.89])

In [70]:
remainder, whole_part = np.modf(arr_float)

### remainder contains the decimal values

In [71]:
remainder

array([0.23, 0.56, 0.89])

### whole_part contains the integral values

In [72]:
whole_part

array([1., 4., 7.])

### applying sqrt function

In [74]:
np.sqrt(arr)

array([3.        , 2.44948974, 2.82842712, 1.41421356, 0.        ,
       1.        ])

In [75]:
arr

array([9, 6, 8, 2, 0, 1])

In [76]:
np.square(arr)

array([81, 36, 64,  4,  0,  1], dtype=int32)

### creating a 2D array from two 1D array using np.meshgrid

In [80]:
xs,ys = np.meshgrid(arr,arr)

In [78]:
xs

array([[9, 6, 8, 2, 0, 1],
       [9, 6, 8, 2, 0, 1],
       [9, 6, 8, 2, 0, 1],
       [9, 6, 8, 2, 0, 1],
       [9, 6, 8, 2, 0, 1],
       [9, 6, 8, 2, 0, 1]])

In [79]:
ys

array([[9, 9, 9, 9, 9, 9],
       [6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8],
       [2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1]])

### xs is row wise, and ys is column wise
